version: '3.9'

services:
  db:
    image: mariadb:10.11.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: mypassword
    volumes:
      - db:/var/lib/mysql
    healthcheck:
     test: ["CMD","mysqladmin","ping","-h","localhost","-pmypassword"]
     start_period: 5s
     interval: 5s
     timeout: 5s
     retries: 20
    networks:
      - backend
  nextcloud:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    depends_on:
     db:
      condition: service_healthy
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: mypassword
    volumes:
      - nextcloud:/var/www/html
    ports:
      - "8080:80"
    networks:
      - backend
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always
    depends_on:
      - nextcloud
    networks:
      - backend
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus
    networks:
      - backend

networks:
  backend:

volumes:
  db:
  nextcloud:
